language: node_js
node_js:
  - "8"
  - "9"

cache: yarn

before_install:
  - npm i -g npm@6.3.0
  - npm i jest react react-dom react-router-dom prop-types oidc-client

install: yarn
script:
  - yarn test

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "8"
      script: yarn compile
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true

# variables d'env
env:
  global:
    - NODE_ENV=production