language: node_js

node_js:
  - "8"
  - "9"

# échoue dès qu'une erreur intervient
matrix:
  fast_finish: true

before_install:
  - npm install react@16.4 react-scripts oidc-client react-router-dom recompose 

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "8"
      script: yarn compile
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true

# variables d'env
env:
  global:
    - NODE_ENV=production